Track Metrics About Tokenization Results
sambanova/generative_data_prep pull request #44
Opened 2023-10-02 23:01 UTC by snova-zoltanc

## Summary
There are a lot of metadata details about the dataset that would be useful to know, but it would require writing non trivial python script to extract that from the hdf5 files. So lets keep track of all this metadata and print it so the use can learn more about their resulting dataset

## PR Checklist
- [ X] My PR is less than 500 lines of code
- [X ] I have added sufficient comment as docstrings in my code
- [X ] I have made corresponding changes to the documentation

- [ ] I have written unit-tests to test all of my code

2023-10-02 23:08 UTC, snova-zoltanc commented on generative_data_prep/processors/metrics.py
> +        # return tabulate(table, "fancy_outline")
I want to replace this with tabulate to get a nice table print, but I am not sure how to get the dependency working. I asked @snova-ranjanl to help

2023-10-03 04:42 UTC, snova-zoltanc commented
![image](https://github.com/sambanova/generative_data_prep/assets/137233191/6bc21c44-581f-452e-849f-4865e410ebd6)

Create a nice table for tracking dataset metrics.

2023-10-03 22:25 UTC, snova-ranjanl requested changes
Looks good overall, and needs a few tweaks.

Regarding the `hdf5` binary files, do we need these here or are these merely artifacts?

2023-10-03 22:25 UTC, snova-ranjanl commented on .pre-commit-config.yaml
> +      additional_dependencies: [types-tabulate]
we should be able to add this setting to `pyproject.toml` instead.

2023-10-03 22:25 UTC, snova-ranjanl commented on generative_data_prep/data_prep/data_prep.py
> +    # lets return an object here that stores all the metrics we want to track
nit: should this comment go to the function-docstrings instead?

2023-10-03 23:47 UTC, snova-ranjanl commented
@snova-zoltanc actually, your `additional_dependency` for `tabulate` is fine to be in the `pre-commit` config file.

2023-10-03 23:56 UTC, snova-ranjanl approved these changes
looks good if it passes all CI

2023-10-06 21:48 UTC, snova-virens approved these changes
Looks great!

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/tokenized_line/tokenized_line.py
> +        """The number of completion tokens in this sequence."""
typo in docstring

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/processors/metrics.py
> +        self.total_tokens += new_metrics.total_tokens
could we rename this to self.output_tokens?

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/processors/article_tokenizer.py
> +            filtered_sequences.append(line)
could we add a brief comment explaining the bottom two lines

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/processors/article_tokenizer.py
>              if TokenTypeIds.COMPLETION not in line.dump_token_type_ids():
move the sum here.

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/processors/metrics.py
> +        return (self.prompt_tokens + self.completion_tokens) / self.input_tokens
shouldn't this just be self.output_tokens / self.input_tokens?

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/processors/metrics.py
> +        return (self.prompt_tokens + self.completion_tokens) / self.input_tokens
ohhh u're excluding padding, that's smart

2023-10-06 21:48 UTC, snova-virens commented on generative_data_prep/processors/metrics.py
> +Article tokenizer takes any input text or jsonl, runs tokenization using
Please fix this

2023-10-06 23:02 UTC, snova-virens approved these changes
Thanks Zoli!

2023-10-06 23:07 UTC, snova-ranjanl approved these changes

2023-10-06 23:07 UTC, merged