Implement absolute path to logging config file
sambanova/generative_data_prep pull request #56
Opened 2023-10-27 18:52 UTC by snova-zoltanc

Currently the config file path is a relative path to current working directory, this will cause this repo to fail out if the user runs from any other directory.

## Summary
Generate the config file path as an absolute path from the file in the repo.

## PR Checklist
- [X] My PR is less than 500 lines of code
- [X] I have added sufficient comment as docstrings in my code
- [X] I have made corresponding changes to the documentation

2023-10-27 18:58 UTC, snova-virens submitted a review, later dismissed
Nice :)

2023-10-27 20:00 UTC, snova-ranjanl requested changes

2023-10-27 20:00 UTC, snova-ranjanl commented on generative_data_prep/__main__.py
> +    logging.config.fileConfig(get_config_file_path())
please move `configs` inside `generative_data_prep`; placing it outside causes all sorts of issues

2023-11-09 23:21 UTC, snova-ranjanl commented
closing this as this was implemented by https://github.com/sambanova/generative_data_prep/pull/58

2023-11-09 23:21 UTC, closed without merging